/* generated configuration header file - do not edit */
#ifndef R_RTC_CFG_H_
#define R_RTC_CFG_H_
#define RTC_CFG_PARAM_CHECKING_ENABLE (BSP_CFG_PARAM_CHECKING_ENABLE)
#define RTC_CFG_MULTIPLEX_INTERRUPT_SUPPORTED (0)
#if RTC_CFG_MULTIPLEX_INTERRUPT_SUPPORTED
 #define RTC_CFG_MULTIPLEX_INTERRUPT_ENABLE         BSP_INTERRUPT_ENABLE
 #define RTC_CFG_MULTIPLEX_INTERRUPT_DISABLE        BSP_INTERRUPT_DISABLE
#else
 #define RTC_CFG_MULTIPLEX_INTERRUPT_ENABLE
 #define RTC_CFG_MULTIPLEX_INTERRUPT_DISABLE
#endif
#endif /* R_RTC_CFG_H_ */
